# Generated by Django 3.1.4 on 2021-01-11 02:55

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='based_in',
            new_name='basedin',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_design',
            new_name='desc_design',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_short',
            new_name='desc_short',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='website_link',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=portfolio.models.get_image_filename, verbose_name='Image'),
        ),
    ]
