# Generated by Django 3.1.4 on 2021-01-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210114_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=2500)),
                ('title', models.CharField(max_length=2500)),
                ('about', models.TextField(blank=True, max_length=2500, null=True)),
                ('email', models.CharField(blank=True, max_length=2500)),
                ('btn1link', models.CharField(blank=True, max_length=2500)),
                ('profile_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
